apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: bdrck-otel-instrumentation
  namespace: observability
spec:
  exporter:
    endpoint: http://bdrck-cluster-monitor-opentelemetry-collector.observability.svc.cluster.local:4317
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  java:
